name: Tests
on: pull_request

jobs:
    markdownlint:
        name: Lint markdown
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout project
              uses: actions/checkout@v1
            - name: Cache dependencies
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: npm-cache
            - name: Install dependencies
              run: npm install
            - name: Lint markdown
              run: npm run lint:md
